# Generated by Django 2.2.5 on 2019-09-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default='defaultshortcode', max_length=15),
            preserve_default=False,
        ),
    ]
