# Generated by Django 2.2.5 on 2020-01-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickevent',
            old_name='Kirr_url',
            new_name='kirr_url',
        ),
    ]
